/* Simulation code for Dut generated by the OpenModelica Compiler OpenModelica v1.20.0 (64-bit). */
#if !defined(Dut__MODEL_H)
#define Dut__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "util/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Dut_functions.h"

#define Dut_angleToTorqueAdaptor_move_position__der2_index 0

extern void Dut_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Dut_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Dut_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Dut_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Dut_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Dut_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Dut_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Dut_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Dut_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Dut_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Dut_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Dut_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Dut_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Dut_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Dut_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Dut_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Dut_relationDescription(int i);
extern void Dut_function_initSample(DATA *data, threadData_t *threadData);
extern int Dut_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Dut_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Dut_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Dut_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Dut_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Dut_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Dut_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Dut_linear_model_frame(void);
extern const char* Dut_linear_model_datarecovery_frame(void);
extern int Dut_mayer(DATA* data, modelica_real** res, short *);
extern int Dut_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Dut_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Dut_setInputData(DATA *data, const modelica_boolean file);
extern int Dut_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Dut_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Dut_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Dut_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Dut_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Dut_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Dut_inputNames(DATA* data, char ** names);
extern int Dut_dataReconciliationInputNames(DATA* data, char ** names);
extern int Dut_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Dut_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Dut_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Dut_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Dut__MODEL_H) */


