/* Simulation code for SetInput generated by the OpenModelica Compiler OpenModelica v1.20.0 (64-bit). */
#if !defined(SetInput__MODEL_H)
#define SetInput__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "util/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "SetInput_functions.h"


extern void SetInput_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void SetInput_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int SetInput_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int SetInput_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int SetInput_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SetInput_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SetInput_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int SetInput_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int SetInput_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int SetInput_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int SetInput_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int SetInput_checkForAsserts(DATA *data, threadData_t *threadData);
extern int SetInput_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int SetInput_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int SetInput_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* SetInput_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* SetInput_relationDescription(int i);
extern void SetInput_function_initSample(DATA *data, threadData_t *threadData);
extern int SetInput_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SetInput_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SetInput_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SetInput_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SetInput_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SetInput_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SetInput_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* SetInput_linear_model_frame(void);
extern const char* SetInput_linear_model_datarecovery_frame(void);
extern int SetInput_mayer(DATA* data, modelica_real** res, short *);
extern int SetInput_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int SetInput_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int SetInput_setInputData(DATA *data, const modelica_boolean file);
extern int SetInput_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void SetInput_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void SetInput_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int SetInput_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void SetInput_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void SetInput_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int SetInput_inputNames(DATA* data, char ** names);
extern int SetInput_dataReconciliationInputNames(DATA* data, char ** names);
extern int SetInput_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int SetInput_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int SetInput_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "SetInput_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(SetInput__MODEL_H) */


