/* Additional record code for DutMonitor generated by the OpenModelica Compiler OpenModelica v1.20.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "DutMonitor_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

